CREATE DATABASE CYBER_AGGRESSION;

USE CYBER_AGGRESSION;

CREATE TABLE USERS (
ID INT Auto_Increment PRIMARY KEY,
USERNAME VARCHAR(100) UNIQUE,
PASSWORD VARCHAR(255)
);

CREATE TABLE ADMINS(
ID INT Auto_Increment PRIMARY KEY,
USERNAME VARCHAR(100) UNIQUE,
PASSWORD VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS abusers (
ID INT Auto_Increment PRIMARY KEY,
USERNAME VARCHAR(50) NOT NULL UNIQUE,
VIOLATIONS INT NOT NULL
);

CREATE TABLE IF NOT EXISTS blocked_messages (
ID INT Auto_Increment PRIMARY KEY,
USERNAME VARCHAR(50) NOT NULL,
message TEXT NOT NULL
);

CREATE TABLE friend_requests (
ID INT Auto_Increment PRIMARY KEY,
sender VARCHAR(50),
receiver VARCHAR(50),
status VARCHAR(20) DEFAULT 'pending'

);
CREATE TABLE friends (
ID INT Auto_Increment PRIMARY KEY,
user1 VARCHAR(50) ,
user2 VARCHAR(50) 

);